[package]
name = "libarchive2-sys"
version = "0.1.0"
edition = "2024"
links = "archive"
build = "build.rs"

[dependencies]

[build-dependencies]
bindgen = "0.72"
cmake = "0.1"
which = "8.0"
cc = "1.2"
